"""initial schema

Revision ID: a672ec5f90ad
Revises:
Create Date: 2026-10-04 18:08:40.025985

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a672ec5f90ad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "barbell_unit",
        sa.Column("variant", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chrono_unit",
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_unit",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "martial_arts_unit",
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("end_t", sa.Time(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rope_skip_unit",
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "running_unit",
        sa.Column("distance", sa.Double(), nullable=False),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "swimming_unit",
        sa.Column("distance", sa.Double(), nullable=False),
        sa.Column("pool_length", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_unit",
        sa.Column("start_t", sa.Time(), nullable=True),
        sa.Column("end_t", sa.Time(), nullable=True),
        sa.Column("seconds", sa.Double(), nullable=True),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("project", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "barbell_set",
        sa.Column("set_nr", sa.Integer(), nullable=False),
        sa.Column("rest", sa.Double(), nullable=False),
        sa.Column("weight", sa.Double(), nullable=False),
        sa.Column("reps", sa.Double(), nullable=False),
        sa.Column("fk_unit", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_unit"],
            ["barbell_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("unit_setting")
    op.drop_table("cardio_unit")
    op.drop_table("unit_category")
    op.drop_table("gym_unit")
    op.drop_table("lifting_set")
    op.add_column("lifting_unit", sa.Column("start_t", sa.Time(), nullable=False))
    op.add_column("lifting_unit", sa.Column("end_t", sa.Time(), nullable=False))
    op.add_column("lifting_unit", sa.Column("gym", sa.String(), nullable=False))
    op.add_column("lifting_unit", sa.Column("name", sa.String(), nullable=False))
    op.add_column("lifting_unit", sa.Column("spartan_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("lifting_unit_unit_setting_id_fkey"), "lifting_unit", type_="foreignkey"
    )
    op.create_foreign_key(None, "lifting_unit", "spartan", ["spartan_id"], ["id"])
    op.drop_column("lifting_unit", "variant")
    op.drop_column("lifting_unit", "unit_setting_id")
    op.drop_column("lifting_unit", "program")
    op.add_column("spartan", sa.Column("email", sa.String(), nullable=False))
    op.add_column("spartan", sa.Column("hashed_password", sa.String(), nullable=False))
    op.add_column("spartan", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("spartan", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.add_column(
        "spartan", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_index(op.f("ix_spartan_email"), "spartan", ["email"], unique=True)
    op.add_column("wimhof_unit", sa.Column("zen_mode", sa.Boolean(), nullable=False))
    op.add_column("wimhof_unit", sa.Column("guide", sa.String(), nullable=True))
    op.add_column("wimhof_unit", sa.Column("name", sa.String(), nullable=False))
    op.add_column("wimhof_unit", sa.Column("spartan_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("wimhof_unit_unit_setting_id_fkey"), "wimhof_unit", type_="foreignkey"
    )
    op.create_foreign_key(None, "wimhof_unit", "spartan", ["spartan_id"], ["id"])
    op.drop_column("wimhof_unit", "unit_setting_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wimhof_unit",
        sa.Column("unit_setting_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "wimhof_unit", type_="foreignkey")
    op.create_foreign_key(
        op.f("wimhof_unit_unit_setting_id_fkey"),
        "wimhof_unit",
        "unit_setting",
        ["unit_setting_id"],
        ["id"],
    )
    op.drop_column("wimhof_unit", "spartan_id")
    op.drop_column("wimhof_unit", "name")
    op.drop_column("wimhof_unit", "guide")
    op.drop_column("wimhof_unit", "zen_mode")
    op.drop_index(op.f("ix_spartan_email"), table_name="spartan")
    op.drop_column("spartan", "created_at")
    op.drop_column("spartan", "is_admin")
    op.drop_column("spartan", "is_active")
    op.drop_column("spartan", "hashed_password")
    op.drop_column("spartan", "email")
    op.add_column(
        "lifting_unit",
        sa.Column("program", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "lifting_unit",
        sa.Column("unit_setting_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "lifting_unit",
        sa.Column("variant", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "lifting_unit", type_="foreignkey")
    op.create_foreign_key(
        op.f("lifting_unit_unit_setting_id_fkey"),
        "lifting_unit",
        "unit_setting",
        ["unit_setting_id"],
        ["id"],
    )
    op.drop_column("lifting_unit", "spartan_id")
    op.drop_column("lifting_unit", "name")
    op.drop_column("lifting_unit", "gym")
    op.drop_column("lifting_unit", "end_t")
    op.drop_column("lifting_unit", "start_t")
    op.create_table(
        "lifting_set",
        sa.Column("set_nr", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "reps",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rest",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("fk_unit", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_unit"], ["lifting_unit.id"], name=op.f("lifting_set_fk_unit_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lifting_set_pkey")),
    )
    op.create_table(
        "gym_unit",
        sa.Column("start_t", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column("end_t", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column("gym", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("training", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("focus", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "log_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("unit_setting_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_setting_id"],
            ["unit_setting.id"],
            name=op.f("gym_unit_unit_setting_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("gym_unit_pkey")),
    )
    op.create_table(
        "unit_category",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("unit_category_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("unit_category_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "cardio_unit",
        sa.Column("start_t", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column(
            "seconds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "distance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("avg_hr", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("max_hr", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("calories", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "log_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("unit_setting_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_setting_id"],
            ["unit_setting.id"],
            name=op.f("cardio_unit_unit_setting_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cardio_unit_pkey")),
    )
    op.create_table(
        "unit_setting",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["unit_category.id"],
            name=op.f("unit_setting_category_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("unit_setting_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("unit_setting_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("barbell_set")
    op.drop_table("work_unit")
    op.drop_table("swimming_unit")
    op.drop_table("running_unit")
    op.drop_table("rope_skip_unit")
    op.drop_table("martial_arts_unit")
    op.drop_table("log_unit")
    op.drop_table("chrono_unit")
    op.drop_table("barbell_unit")
    # ### end Alembic commands ###
