emojis = {
    b"\xe2\x9a\x96\xef\xb8\x8f".decode(): "balance",
    b"\xf0\x9f\xaa\x90".decode(): "wimhof",
    b"\xf0\x9f\xa6\x8d".decode(): "weights",
    b"\xe2\x98\xaf\xef\xb8\x8f".decode(): "yoga",
    b"\xe2\x9b\xa9\xef\xb8\x8f".decode(): "squat",
    b"\xf0\x9f\x8f\x97\xef\xb8\x8f".decode(): "deadlift",
    b"\xf0\x9f\x9a\x81".decode(): "benchpress",
    b"\xf0\x9f\xa6\xad".decode(): "overheadpress",
    b"\xf0\x9f\x90\xa2".decode(): "rows",
    b"\xf0\x9f\xa6\x85".decode(): "pullups",
    b"\xf0\x9f\x8c\x90".decode(): "pushups",
    b"\xf0\x9f\xaa\x96".decode(): "running",
    b"\xf0\x9f\x90\xa7".decode(): "rowing",
    b"\xf0\x9f\x9a\xb2".decode(): "cycling",
    b"\xf0\x9f\xa6\x88".decode(): "swimming",
    b"\xf0\x9f\xa4\xba".decode(): "skipping",
    b"\xe2\x9a\x94\xef\xb8\x8f".decode(): "splitmachine",
    b"\xf0\x9f\x8f\xb9".decode(): "stretch",
    b"\xf0\x9f\x94\xa5".decode(): "naulikriya",
    b"\xf0\x9f\x90\xa7".decode(): "tek",
    b"\xf0\x9f\x93\xa1".decode(): "study",
    b"\xf0\x9f\xa6\x89".decode(): "reading",
}
