"""initial schema

Revision ID: f45d2824cbd4
Revises:
Create Date: 2026-10-09 17:25:21.855415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f45d2824cbd4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spartan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spartan_email"), "spartan", ["email"], unique=True)
    op.create_index(op.f("ix_spartan_username"), "spartan", ["username"], unique=True)
    op.create_table(
        "unit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("spartan_id", sa.Integer(), nullable=False),
        sa.Column("unit_type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("log_time", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["spartan_id"],
            ["spartan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "barbell_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variant", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chrono_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lifting_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("end_t", sa.Time(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "martial_arts_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("end_t", sa.Time(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "running_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Double(), nullable=False),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skipping_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "swimming_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Double(), nullable=False),
        sa.Column("pool_length", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("start_t", sa.Time(), nullable=False),
        sa.Column("seconds", sa.Double(), nullable=False),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wimhof_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zen_mode", sa.Boolean(), nullable=False),
        sa.Column("guide", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_t", sa.Time(), nullable=True),
        sa.Column("end_t", sa.Time(), nullable=True),
        sa.Column("seconds", sa.Double(), nullable=True),
        sa.Column("gym", sa.String(), nullable=False),
        sa.Column("project", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "barbell_set",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("set_nr", sa.Integer(), nullable=False),
        sa.Column("rest", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Double(), nullable=False),
        sa.Column("reps", sa.Double(), nullable=False),
        sa.Column("fk_unit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_unit"],
            ["barbell_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wimhof_round",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("round_nr", sa.Integer(), nullable=False),
        sa.Column("breaths", sa.Integer(), nullable=False),
        sa.Column("retention", sa.Integer(), nullable=False),
        sa.Column("fk_unit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_unit"],
            ["wimhof_unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wimhof_round")
    op.drop_table("barbell_set")
    op.drop_table("work_unit")
    op.drop_table("wimhof_unit")
    op.drop_table("swimming_unit")
    op.drop_table("skipping_unit")
    op.drop_table("running_unit")
    op.drop_table("martial_arts_unit")
    op.drop_table("log_unit")
    op.drop_table("lifting_unit")
    op.drop_table("chrono_unit")
    op.drop_table("barbell_unit")
    op.drop_table("unit")
    op.drop_index(op.f("ix_spartan_username"), table_name="spartan")
    op.drop_index(op.f("ix_spartan_email"), table_name="spartan")
    op.drop_table("spartan")
    # ### end Alembic commands ###
