
# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checokut code
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --without=DEV

      - name: Run Ruff
        run: |
          poetry run ruff format .
          poetry run ruff check --fix .
      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Ruff Format" || true
          git push

      - name: Run Ruff Check
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run pytest tests

