name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install uv
        run: pip install uv

      - name: Install Dependencies
        run: uv sync

      - name: Run Ruff check
        run: uv run ruff check .

      - name: Run Typechecker
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest tests

      - name: Build Package
        run: uv build
