name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --without=dev

      - name: Run Ruff check
        run: poetry run ruff check .

      - name: Run Typechecker
        run: poetry run mypy .

      - name: Run tests
        run: poetry run pytest tests

      - name: Build Package
        run: poetry build
